### ISSUE TITLE
Adding proper Dockerfile and docker-compose architecture

### ISSUE THREAD

**Issue by flavienbwk** [prologic/twtxt#18]
## What is good

- This project is Docker-runnable for runtime !
- This project is great

## What is not right

1. Currently, the Dockerfile includes this line : `COPY . .`. This is a red flag in a Docker project showing a unfriendly Docker architecture.
2. The `RUN make deps build` line after the `COPY . .` line re-downloads the dependencies.
3. There is no `docker-compose.yml` file, nor a section in the documentation showing what `docker run` command we can run to deploy the project.

## Why this is not right

1. Imagine you edit one character in your README.md, or any file that has nothing to do with the source code : your project will need to be entirely re-built. So if you have a Docker pipeline to automatically push your image to the Docker hub, you will have a lot of useless images. It would not be clean.
2. You should first `make deps`, then copy source code `COPY . .` and then build the sources `make build`. Otherwise your image build always re-downloads the same dependencies. It's a loss of time and resources.
3. If we want the project to be easily deployable, we want to have a docker-compose configuration file

Additionaly, the documentation doesn't mention how to run the Docker version of this project

## Improvements

I see the `make build` rule re-downloads a lot of dependencies. You may want to add these in the `make deps` rule, or mount the dependencies as a volume to avoid re-downloading every time these dependencies. As I am not really familiar with Go, I don't know if this is possible and/or where the dependencies directory is located.

## Related PR

[19](https://github.com/prologic/twtxt/pull/19)

## Warning

Please @prologic check if this configuration doesn't break any _go report_, _.github_ or _codebeat_ CI processes

**Comment by prologic** [comment]
Thanks for the PR @flavienbwk much appreciated! You are right about the invalidating the Docker build cache. I was a bit lazy here and launched all this quite quickly (_just a few days ago!_). Those changes should definitely go in so that building and rebuilding is always fast.

I'm not so keen on just `mv *.go src/` however as this is an unfamiliar structure to me with a lot of Go projects I've written over the years -- Although I've seen some that use an entirely different layout with `./pkg/...`. I'm more in favour of moving everything into the special `internal` package since most of the code as it is right now is not really re-useable as Go imports (_without a lot of cleanup/work, which we should also do_).

If you can resolve the conflicts on #19 I'll definitely take a look!

**Comment by prologic** [comment]
Can we do this a different way?

For example:

```#!Dockerfile
.
.
.
COPY *.go /src/
.
.
.
```

I _think_ this will still respect and utilise the Docker build cache.

**Comment by prologic** [comment]
@flavienbwk Based on your feedback and very valid suggestions I took apart your original PR #19 and reworked into into smaller PRs that didn't break the code layout, imports but still kept in tact many of the intends you had with this issue.

The only part I didn't take was the README documentation updates. If you could submit a PR to update those to your liking I would appreciate it. I personally don't actually develop with `docker-compose` so I would not be the best person to document this.

Thanks :)
