### ISSUE TITLE
Not understanding replies

### ISSUE THREAD

**Issue by flavienbwk** [prologic/twtxt#32]
Hi,

I would like to know more about replies as I am a bit confused with them : when I reply to a post, I am expecting to see the post I am replying to in my reply.

From what I understand, currently "replies" are just pre-filling a `@mention` to the person I want to reply to in a post. So it's like a chat ?

Thank you for the clarifications

**Comment by prologic** [comment]
Right now yes its just a convenience. A UI/UX thing because I found it tedious myself to have to copy/paste or remember someone's username I was replying to. This can of course be improved; but bare in mind that [twtxt](https://twtxt.readthedocs.org) which [twtxt.net](https://twtxt.net) is based around (_I'm just taking it a lot further I guess?_) is pretty simple. Therefore the only thing that makes sense IHMO is for someone with much better UI/UX skills than me to come along and improve the experience such that the post you are replying to can be above the text input in some nice way so you have a refernece.

Make sense?

But for now yes its' just pre-filling the person that wrote the post you are replying to.

The convention generally I've found in the `twtxt` community is to do something like:

```
@person (re some short thing) your response
```

**Comment by flavienbwk** [comment]
I understand.

I think something like this should be sufficient : 

![image](https://user-images.githubusercontent.com/14158127/88452675-f329b300-ce60-11ea-89de-381a62b7f31d.png)

**Comment by prologic** [comment]
Do you happen to have the UI/UX / CSS skills to pull this off? That would be awesome :) (_I don't really, I've done the best I can so far with the tools I have_ -- I'm really an Infrastructure/Backend/SRE Engineer_)

**Comment by flavienbwk** [comment]
I had to work on UI/UX for a previous company but for this one it's more about an intuition ! However, I am not sure that every message has an _hash_. I've seen in the code that they have an `URL` (`Tweeter.URL`) but I am not sure it is pointing to a specific post. If not, we could not immediately/easily propose this feature.

**Comment by prologic** [comment]
Linking to posts is actually really hard to do. If you read the [twtxt](https://twtxt.readthedocs.org) spec you'll see that there is no mention of:

- Order of posts in a file (_newest at the bottom, append-only or newest at the top_)
- Immutability (_meaning that anyone can edit their `twtxt.txt` file_)

These two things alone break any ability to reliably "hash" a post and use it in future references or link to it. I have ideas for [twtxt.net](https://twtxt.net) specifically where I _could_ do some clever things with the feed cache and keep a chain of hashes in case we discover posts' content we've seen before changes; but that's a story for another day.

I will close this issue for now :) If a UI/UX guy comes along that wants to improve this part of the UI then I would be trhilled!

**Comment by flavienbwk** [comment]
I am not sure this has to do with UI/UX : it is quite back-end related. You will have at a moment to introduce a way to point to a specific post if you want to have this feature.

**Comment by prologic** [comment]
> @prologic I am not sure this has to do with UI/UX : it is quite back-end related. You will have at a moment to introduce a way to point to a specific post if you want to have this feature.

A way to ref and link to specific posts is coming too. I have ideas for this that I need to write down into a proper Issue and implement. But basically the basic idea is to hash the content of the post we fetch in the global cache and use this to ref/link to. If on subsequent fetches we find the content has changed that's okay we just store both and the hash ref/link to the old content still works.

**Comment by flavienbwk** [comment]
Why not yes!
