### ISSUE TITLE
Session expiration time needs some tweaking + 'Remember me' option?

### ISSUE THREAD

**Issue by lwojcik** [prologic/twtxt#41]
Me and twtxt authentication mechanism are having issues today. I had to rewrite two twets (twts?) because my session expired too soon, effectively forming a habit of copying twet content before hitting 'send' in case it gets dropped. :)

I believe at least one remediation is needed:

* extending session expiration time,
* adding 'Remember me' option on login,
* leaving session expiration time unchanged but making the mechanism 'remember' portions of application state - i.e. attempt to post a twet once I login? 
* some other way to make it more, uhm, user-friendly?

**Comment by prologic** [comment]
So I find this annoying too! (_sorry about that!_) Let's fix this!

So couple of things here;

- I wrote most of the session handling and auth handling code (_or least I think I did quite some time ago on another project that went nowhere, so borrowed it here_)
- That old project that went nowhere had a "Remember  Me" "think" but I forget how it worked or I never implemented it.
- The only session store at this point is an in-memory one; one of the reasons users (_and there are now ~54 of them!, not sure how many active though_) get booted out is I keep constantly making commits, and redeploying and  iterating quickly.

So...

I need some help actually because I (_for reasons unknown_) have forgotten a few things over the yeras:

- Why do we have to timeout the session in the first place? Can't we just have an indefinite session?
- If no, how does a "Remember Me" thing work again?
- Is it worth moving the session store to more durable/persistent storage?

**Comment by lwojcik** [comment]
Fast iterations combined with in-memory session store definitely sound like a reason for that.

About the questions you raised, let me think.

* [OWASP cheatsheet on session expiration](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#Session_Expiration). Tl;dr: security aspects.

Indefinite session is generally not recommended, but I do see numerous services using very long timeouts (e.g. Hacker News sets a cookie with 10-year expiration date). It's highly dependent on risk factor vs convenience. Gmail / Twitter can set long timeouts because they have relatively strong security measures against different kinds of attacks. Hacker News does it because there isn't much value in stealing their session cookie anyway.

The aspect of security will be more and more important over time, as more users will come to use the service (sooner or later some of them might turn out to be malicious actors / spammers). But there's also an aspect of convenience. I don't mind seeing the login screen on a desktop, as my password manager will help me get back to track quickly. But it might be much less convenient / more frustrating on a mobile device.

* correct me if I'm wrong, but 'Remember Me' probably sets expiration dates long enough to be pseudo-infinite aka irrelevant.

* I don't have opinion on that yet. It would definitely decrease the number of times users have to re-login, especially when new iterations happen often. It may also be needed with the arrival of API or OS-specific clients / mobile apps. But moving sessions to persisent storage probably comes with the challenge of maintaining and expiring tokens manually vs relying on memory doing the thing.

**Comment by prologic** [comment]
Thanks for the input! I'll have to do a bit of reading on this myself because as I said, I've forgotten some aspects of this...

What are your gut instincts on what we should do here btw?

I  _think_ for the time being I can reconfigure the [twtxt.net](https://twtxt.net) instance to have a longer expiry time on session cookies as a stop-gap while we come up with more viable long-term solutions...

I also don't necessary _think_ implementing another persistent store for sessions that persist between restarts/redeployments is all that  hard personally. It _would_ help a bit in this phase of "fast iteration". I would use the same Bitcask KV store as the backend (_which we use now for user accounts_) and have a periodic background job that runs every say ~5m to cleanup old sessions that exceed their expiry.

**Comment by prologic** [comment]
A comment I found from [this Stackoverflow question](https://stackoverflow.com/questions/3302258/making-sessions-cookies-indefinite)

> I'd honestly suggest implementing a "remember me" function rather than trying to persist the session indefinitely... The remember me would use a cookie as well, but it wouldn't tie up server space for non-active users...

This is how _thought_ "Remember Me" worked. You end up with two cookies:

- A temporary session cookie that expires when your browser session ends.
- A more permanent (_with some longer expiry time_) that the server backend recognises and logs you back in and creates a new temporary session for you.

Honestly though, the _amount_ of data being stored in memory on the session store is minimal at best here anyway, so "tying up backend memory" isn't so much of a concern here.

So I'm more inclined to just increase the session timeout to a much longer value and build a persistent store.

**Comment by lwojcik** [comment]
At this point I believe good user experience is just as important as security, so I'm in favor of extending session timeouts and persistent storage.

**Comment by prologic** [comment]
Turns out I already have the code for persistent session storage, I just didn't realise :) I'll see if I can get this happenning in a few hours and deployed!
