### ISSUE TITLE
[enhancement] dark mode should stick

### ISSUE THREAD

**Issue by marado** [prologic/twtxt#6]
If you click around on the website, and want to be using dark mode, then you will soon be fed up with the fact that at each page change you need to click on 'dark mode' again.

**Comment by prologic** [comment]
I _think_ this might be a bug or something I missed when using [PicoCSS](https://picocss.com) I'll see if I can repro this locally.

**Comment by prologic** [comment]
Hmm 🤔 I can't actually reproduce this. What browser/environment did you see this in?

In a fresh Incognito session on macOS with Chrome I can visit every view and the theme (dark or light) persists.

What browser/environment did you see this in?

**Comment by prologic** [comment]
Ahh no wait I can reproduce this. Never-mind! I'll look into why this is happening, probably something I did wrong.

**Comment by prologic** [comment]
@lucaslarroche Are you able to help with this since I'm using your [PicoCSS](https://picocss.com)? Thanks!

**Comment by lucaslarroche** [comment]
Saving user preferences has not been coded in Pico because this requires JS and Cookies.

The Dark theme is automatically enabled only if user has dark mode enabled `prefers-color-scheme: dark`.
But themes can be forced with `<html data-theme="light">` or `<html data-theme="dark">`.

In your case, you have to store the user preference on click in cookies then read the cookie each time you load a page to attribute `data-theme`.

**Comment by prologic** [comment]
> In your case, you have to store the user preference on click in cookies then read the cookie each time you load a page to attribute data-theme.

This is what I was missing. Thank you 🙇‍♂️
