### ISSUE TITLE
Caching is broken

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#64]
Basically as I Twt'd [Caching is quite broken](https://twtxt.net/#wnmyerjmcyclj4li55lra2omavuy5dsd3ldwc2u7xassgfkcw6uq)

There is basically no `Cache-Control` or `ETag` on any of the endpoints or static assets; so whatever sits in front just does whatever it wants :/ 

This hurts the user experience (_especially now with new custom Avatars_)

**Comment by dooven** [comment]
Just trying to test etags out. I made this [branch ](https://github.com/prologic/twtxt/compare/master...dooven:e-tag)

Where the avatar didnt get changed it will just return 304
![Screenshot from 2020-07-31 20-53-54](https://user-images.githubusercontent.com/15314237/89092627-8a669d00-d370-11ea-81c8-0318bc0916fb.png)

Then if you change the avatar, it will give you the latest one
![Screenshot from 2020-07-31 20-55-07](https://user-images.githubusercontent.com/15314237/89092639-abc78900-d370-11ea-9b49-9dee9a7f174b.png)

Lmk what your thoughts on it :sweat_smile:

**Comment by prologic** [comment]
I _think_ an `ETag` on the `/user/<username>/avatar.png` is the right approach yes. Put this PR up and let's put it in production and see how CloudFlare behaves :)

**Comment by dooven** [comment]
I dont think the etags is working in twtxt.net. It's not included in the response headers when hitting the avatar endpoint :disappointed: Maybe this is a cloudflare thing?
![Screenshot from 2020-08-01 21-41-34](https://user-images.githubusercontent.com/15314237/89114990-d7fe0b00-d43f-11ea-85cb-bd4f84e8dcf7.png)

**Comment by prologic** [comment]
Hmmm lemme have a look at the Cloudflare settings and see if there's a "knob" for this...

**Comment by dooven** [comment]
Looking at the [docs](https://support.cloudflare.com/hc/en-us/articles/218505467-Using-ETag-Headers-with-Cloudflare)
> set a strong ETag header in quotes (Etag: "example") or Cloudflare removes the ETag instead of converting it to a weak ETag. 
I think i may have to use etag by adding W/"<our_existing_etag>" or wrap our existing etag with quotes. 

I'll open a PR for that

**Comment by prologic** [comment]
I enabled:

- Respect Existing Headers
- Ignore Query String

Hopefully this works for Avatars.

Now just need to make it also work for custom CSS/JS as well and we're good _I think_

**Comment by dooven** [comment]
Still not seeing those etags header. The docs also mentions to disable the email obfuscation setting. https://stackoverflow.com/questions/38034586/cloudflare-not-forwarding-etag-header
> When using weak ETag headers, disable Email Obfuscation and Automatic HTTPS Rewrites to ensure Cloudflare doesn't remove the ETag headers set by your origin web server.
Should we try disabling it?

**Comment by dooven** [comment]
It looks like the etags didnt help with the caching issue. My old avatar is a white background, then i uploaded a new one (gopher). 
After uploading the photo, i went back to the settings page and refreshed it, but i dont see the new photo. 

For some reason the response headers coming from the avatar endpoint is returning the old photo's etag :thinking: 
![out](https://user-images.githubusercontent.com/15314237/89115896-e6055900-d44a-11ea-98f8-90bfa4fc7b79.gif)

**Comment by dooven** [comment]
Maybe it's because we're using the same URL for the avatar /user/<username>/avatar.png, and cloudflare gets confused with it for some reason?  What if we just use the MediaHandler to upload the file, and store the URL of the avatar in our database.

**Comment by prologic** [comment]
@dooven Hmm sorry didn't see the last few comments here... Is this still an issue? (_your last few comments were ~2hrs ago_) LMK!

**Comment by lwojcik** [comment]
I'm not sure where to put this, but some time ago I promised to [check settings section of Cloudflare cache mechanism](https://twtxt.net/user/lukem#uhe7jl7xltc6oyvwbjxw7yqshsxvhgcs54w3cvbcl3bf3xg43esa), so here goes:

* In _Caching > Configuration > Browser Cache TTL_ it's possible to lower cache down to as low as 30 minutes. It's also possible to set it to _Respect existing headers_ which passes control over cache lifetime to the origin server.

* When in doubt, _Purge everything_ button or _Development mode_ switch are usually good calls. Cache purging can also be triggered via an API call. Purge can apply to [the whole zone](https://api.cloudflare.com/#zone-purge-all-files) or [individual URLs](https://api.cloudflare.com/#zone-purge-files-by-url). Based on my previous experience with a side project offloading a lot of work to Cloudflare cache it's definitely worth integrating programmatic cache purge with some processes happening in the app (deployments, users changing their settings etc.), otherwise some users may complain about their changes not being live immediately.

* Exceptions to global cache rules can be applied via _Page Rules_.

Everything I mention above can be done with Cloudflare free tier. Paid tiers offer even more options (e.g. purge by specific host or tag) but I never had a chance to look at them.

**Comment by dooven** [comment]
> @dooven Hmm sorry didn't see the last few comments here... Is this still an issue? (_your last few comments were ~2hrs ago_) LMK!

Yeah.I just updated my avatar, but when go back to the settings page, it's still showing the old one.

**Comment by prologic** [comment]
@dooven How long did it take to finally appear?

Perhaps we do need to trigger Cloudflare APIs and have support for this? But then again I don't really like tying something to a SaaS/Cloud service really because [twtxt.net](http://twtxt.net) wherever you choose to put in front of it should stand alone.

I did change the cache settings to "Repsect Original Headers"; but I guess this isn't enough?

**Comment by dooven** [comment]
It took ~20 mins for my new avatar to appear.

**Comment by prologic** [comment]
Just in case Cloudflare was holding on to some older cached items, I just "Purged Everything". Let's see how things go now we've fixed a bunch of caching issues on the backend! 🤞
