### ISSUE TITLE
How does twtxt compare to Mastodon?

### ISSUE THREAD

**Issue by jtagcat** [prologic/twtxt#86]
How does this compare to Mastodon?

(sorry to challenge the project)

**Comment by prologic** [comment]
Don't apologise! Competition is a healthy thing!

I have to admit I need to go look at Mastodon a bit more closely and do a comparison. But here's what I know and have experienced thus far:

- Mastadon is hard to get going (_at least in my experience_), twtxt.net is not. Single binary, just run it, zero-config, sensible defaults.
- Mastadon is based around ActivityPub, twtxt is based on well um [twtxt](https://twtxt.readthedocs.org) -- However that being said we are open to and exploring the possibility of adding ActivityPub API(s) for interoperability (_WIP, much more thought needed_).
- Both Mastadon and twtxt support short-form posting ala Twitter™ style with similar features such as Following, Following, etc.
- twtxt _does not_ support "direct messaging" (_and probably may never_)

@dooven @aaadonai @shahxeb feel free to add your opinions/experiences here.

**Comment by prologic** [comment]
From Wikipedia:

> Users post (by default[5]) short messages called "toots" for others to see, and can adjust each of their post's privacy settings

twtxt (_that is the software that drives [twtxt.net](https://twtxt.net)_) is a bit different here. Your "feed" is public.

Some unique features twtxt has currently include:

- subFeeds -- Think "sub Redits". Each user is able to create their own "topic of interest" / "subject matter" as a unique feed the behaves the same as if it were another use. They "post as" this feed.
- Access to w ever growing wide range of RSS/Atom feeds that are aggregated into twtxt feeds. So [twtxt.net](https://twtxt.net) also doubles up as a good/nice "news reader".

**Comment by prologic** [comment]
I had another closer look tonight at Mastodon and I can't eve figure out which server to join (_since I don't have one myself obviously_), so that's a bit of a blocker. Hosted "instances" start at ~10 AUD (_I'm from Australia_) for the tiniest spec'd instance per month. Bit steep for something that is effectively just a micro-blogging platform. I pay ~$7 AUD/month for my [Micro.blob](https://micro.blog) [Blog](https://prologic.blog).

Having gone through the [Documentation](https://docs.joinmastodon.org/admin/install/#pre-requisites) on installing and setting up your own I can see already that it's just "way too difficult" for your average person. Maybe that's part the reason you only see ~3k Mastodon instances up and running in the [Fediverse](https://fediverse.network/) 🤷‍♂️

**Comment by felixplesoianu** [comment]
> Some unique features twtxt has currently include:
> 
> * Access to w ever growing wide range of RSS/Atom feeds that are aggregated into twtxt feeds. So [twtxt.net](https://twtxt.net) also doubles up as a good/nice "news reader".

So why can't we skip the middleman and simply follow each other via newsfeed readers as we post to our respective blogs? We'd have tons of advantages: huge ecosystem of applications and libraries already in place, built-in permalinks, metadata, rich formatting without the need for hacks, and probably more I can't think of right now.

Seriously, twtxt strikes me as an exercise in making newsfeeds as simple as possible... and then even simpler. Which is very valuable, but hardly an end goal.

But you invited me to chime in on the whole federation thing. From what I hear, ActivityPub is absurdly huge, vague and complex -- a nightmare to implement -- while MicroPub (actually WebMention, MicroPub is for something else I think) strikes me as a solution in search of a problem. And both were born of programmer hubris, in at least two ways:

1. "XML is icky! Let's replace all of it with JSON! What do you mean, that doesn't solve what's really wrong with APIs?"
2. A mistaken idea that polling feeds at regular interval causes too much needless internet traffic, so we need push instead.

This second point needs expanding. According to at least one study, 60% of all internet traffic is spambots. I wouldn't be surprised if hundreds of readers polling a reasonably-sized newsfeed every five minutes were lighter on the average server. Even without use of HEAD requests. And we don't *need* to poll every five minutes! What the hell! As I wrote in a recent blog post, the idea that we need to know *right now* if someone is talking about us, that's conditioning by social media giants. And it's *not* to our benefit. In fact it's extremely harmful.

So ActivityPub is solving the entirely wrong problem, at the cost of making software exponentially bigger and more complex, eating up more electricity in a warming world and limiting how many people can help make it better. And look how easily we can have an in-depth conversation about this on a glorified forum, that any of us could trivially host on a cheap cPanel account.

**Comment by jtagcat** [comment]
Interoperability would be very nice to see.

> I had another closer look tonight at Mastodon and I can't eve figure out which server to join (_since I don't have one myself obviously_), so that's a bit of a blocker. Hosted "instances" start at ~10 AUD (_I'm from Australia_) for the tiniest spec'd instance per month. Bit steep for something that is effectively just a micro-blogging platform. I pay ~$7 AUD/month for my [Micro.blob](https://micro.blog) [Blog](https://prologic.blog).

Have you seen https://joinmastodon.org/ what is click to pick and register free of charge?

**Comment by jtagcat** [comment]
I use Twitter mostly read-only, so I don't have much say, but twtxt doesn't seem that much of a 'yet an another twitter' now. Thanks.

Maybe link this issue to the readme or somewhere else?

**Comment by prologic** [comment]
> So why can't we skip the middleman and simply follow each other via newsfeed readers as we post to our respective blogs? We'd have tons of advantages: huge ecosystem of applications and libraries already in place, built-in permalinks, metadata, rich formatting without the need for hacks, and probably more I can't think of right now.

If we _could_ we'd have done that already. The problem with an ever evolving society and ever changing tech world is we forget that things like RSS/Atom are a thing and are actually really powerful tools. So yes you are right, when I built [twtxt.net](https://twtxt.net) I set out with two goals in mind: a) Can we build a really simple yet powerful decentralised social network? b) Can I also replace my RSS/Atom (https://commafeed.com at the time) with it?

The answer to both those questions turned out to be "Yes!". Not only that but the first pod https://twtxt.net/ itself has taken off unexpectedly and people really like it, I mean ordinary non-technical folks too!

So I'm going to keep going :) I'm going to try to build out what other Tech Giants never could. Yes Mastodon is kind of similar, but its also very different IHMO; some of your own points I actually fully agree with.

> Seriously, twtxt strikes me as an exercise in making newsfeeds as simple as possible... and then even simpler. Which is very valuable, but hardly an end goal.

Its actually an exercise in creating a self-hosted, decentralised social network that _anyone_ can spin up, join, participate in and enjoy with peace of mind that they can take their data with them to any other pod (_should they wish_), archive their account/feeds or entirely purge them from the Internet.

> 2. A mistaken idea that polling feeds at regular interval causes too much needless internet traffic, so we need push instead.

Yes I don't really believe in this whole "real-time" thing, nor do I _think_ the software that powers [twtxt.net](https://twtxt.net) needs to scale beyond a few hundred users with potentially polling several hundred internal/external feeds. The "scale" will come from interconnected pods.

> So ActivityPub is solving the entirely wrong problem, at the cost of making software exponentially bigger and more complex, eating up more electricity in a warming world and limiting how many people can help make it better. And look how easily we can have an in-depth conversation about this on a glorified forum, that any of us could trivially host on a cheap cPanel account.

The more I hear about AP in the community, here and on #twtxt on FreeNode the most it makes me think we should steer clear of it and just focus on building the thing we originally set out... 🤔

**Comment by prologic** [comment]
> Interoperability would be very nice to see.

I do too. I still _think_ its worth exploring. We may not build a fully AP set of APIs, but maybe enough to interoperate with the rest of the Fediverse (_as its' called?_)?

**Comment by prologic** [comment]
> I use Twitter mostly read-only, so I don't have much say, but twtxt doesn't seem that much of a 'yet an another twitter' now. Thanks.

Do you mind elaborating? I mean I used to have a Twitter account (_funnily enough_) and over the past ~10-15yrs or so I had deleted it, re-created it, deleted it and re-created it again! 😱 As of ~2.5wks  ago since launching twtxt.net I finally nuked itpermanentlyy.

I am and have never been interested in using a platform to express my thoughts and opinions that ultimately use those same thoughts and opinions (_and perhaps hashtags and people I follow_) as a way to fund Jack Dorsey's expensive mansions, yaught, jets and whatever else rich people waste money on!

Its primarily the reason you don't really see me anywhere on traditional "social media" anywhere. I wish not to be their product!

Do you mind also sharing a bit of your thoughts on twtxt vs. Twitter say? I agree its already unique enough and are worlds apart IHMO.

> Maybe link this issue to the readme or somewhere else?

Yes! Meanwhile I'll pin this issue I think as its an important/good debate and discussion!

**Comment by jtagcat** [comment]
> Do you mind elaborating? I mean I used to have a Twitter account (funnily enough) and over the past ~10-15yrs or so I had deleted it, re-created it, deleted it and re-created it again! scream As of ~2.5wks ago since launching twtxt.net I finally nuked itpermanentlyy.

I have deleted, and recreated as well. I use Nitter as a frontend and RSS(!) users, topics, or whatever through it. When I feel like I have a motivated enough reason to **reply** to a tweet, I use the account. Most replies are deleted with the yearly-actually-when-I-feel-like-it prune.

> I am and have never been interested in using a platform to express my thoughts and opinions that ultimately use those same thoughts and opinions (and perhaps hashtags and people I follow) as a way to fund Jack Dorsey's expensive mansions, yaught, jets and whatever else rich people waste money on!

That's also why I didn't adopt Mastodon. I will though, attempt to do stuff similar to https://jlelse.blog/

As for Jack Dorsey, I disagree, but don't feel like elaborating, today at least.

Same with twtxt vs twitter vs mastodon for me. I'll try to reply within a reasonable period.

**Comment by prologic** [comment]
I should also link to my original blog posts on this as well for reference and to help drive the discussion here:
(_in order of when they were posted_)

- [ANN: Announcing twtxt.net - a Web based twtxt client and free micro blogging platform
](https://www.prologic.blog/2020/07/20/ann-announcing-twtxtnet.html)
- [twtxt.net - a Decentralised Self-Hosted Twitter™-like. How and Why.
](https://www.prologic.blog/2020/07/26/twtxtnet-a-decentralized.html)
- [Commercialising twtxt.net?
](https://www.prologic.blog/2020/08/02/commercialising-twtxtnet.html)

**Comment by felixplesoianu** [comment]
> Its actually an exercise in creating a self-hosted, decentralised social network that _anyone_ can spin up, join, participate in and enjoy with peace of mind that they can take their data with them to any other pod (_should they wish_), archive their account/feeds or entirely purge them from the Internet.

Anyone can publish a RSS feed. They can be *handcrafted*. Not as easily as a twtxt feed, which is why I think the simplification exercise is very valuable. And twtxt feeds are a whole lot easier to *consume*. With self-made software, anyway.

But that's not why we like them, right? We like them because they're new and nerdy. Because they're stealthy and make us feel clever. Despite knowing better, we all want to be Hollywood hackers sometimes.

Right now, the only *convenient* way to self-host a twtxt feed is to have a tilde account (or a whole VPS to oneself) and the knowledge to use it. I'm doing it via manual upload to my shared hosting account. It sucks. That twtxt.net is needed in the first place illustrates that simplifying the formats and protocols only solves half the problem. And hosting twtxt.net takes technical chops. Even more than using the current crop of command-line clients.

I have two Mastodon accounts and love them both. Kept meaning to get a third for my real-name self, but couldn't find an instance that felt right for this version of me. As for self-hosting, I'm not in a position to do that, and the effort wouldn't be worth it. Besides, the community aspect of even a small public instance makes a world of difference. And it's for these two reasons that twtxt.net is necessary, valuable... and not nearly as democratic as it seems.

Conversely (and I must go back to this example), I've hosted blogs and forums for my friends in the past, and would do so again in a heartbeat if they wanted one. Anyone with a cPanel account can do it in a few clicks. After two decades of web development, I just happen to have the skills required to do it all manually.

But nobody wants that kind of thing anymore, because forums are passe, "RSS is dead" and tweetstorms are too convenient.

That's our real problem, right there.

**Comment by aaadonai** [comment]
> 
> Anyone can publish a RSS feed. They can be _handcrafted_. Not as easily as a twtxt feed, which is why I think the simplification exercise is very valuable. And twtxt feeds are a whole lot easier to _consume_. With self-made software, anyway.

I think the simplicity around twtxt is the key here. Of course as the software on this repo gets built the challenge will be to keep it simple.

> 
> Right now, the only _convenient_ way to self-host a twtxt feed is to have a tilde account (or a whole VPS to oneself) and the knowledge to use it. I'm doing it via manual upload to my shared hosting account. It sucks. That twtxt.net is needed in the first place illustrates that simplifying the formats and protocols only solves half the problem. And hosting twtxt.net takes technical chops. Even more than using the current crop of command-line clients.
> 
I think the idea is to make twtxt as simple as a click of a button to install, like cPanel, which btw is a proprietary software sold under a license that even if you don't pay for it, your hosting company does.

> Conversely (and I must go back to this example), I've hosted blogs and forums for my friends in the past, and would do so again in a heartbeat if they wanted one. Anyone with a cPanel account can do it in a few clicks. After two decades of web development, I just happen to have the skills required to do it all manually.

cPanel is really good. But I also like how simple it to deploy on Netlify. I think replicating this simplicity would be a good goal for this project. And perhaps use something like Bitnami to easily deploy to a cloud platform.

**Comment by prologic** [comment]
So I decided to _actually_ try Mastodon for real tonight. I've signed up for a fully managed Host instance. I'll try it out and see what its like so I can actually do a fair comparision. Who knows maybe it has some good ideas that _can_ be inspired from 😎

Also I got this (_which is already a differentiator from [twtxt.net](https://twtxt.net) where we plan to fully automate and have 1-click pods that spin up instantaneously).

<img width="809" alt="Screen Shot 2020-08-06 at 22 14 20" src="https://user-images.githubusercontent.com/1290234/89530757-63a5dc00-d832-11ea-89d6-3f5241d9905d.png">

See #87

**Comment by jtagcat** [comment]
> So I decided to _actually_ try Mastodon for real tonight. I've signed up for a fully managed Host instance. I'll try it out and see what its like so I can actually do a fair comparision. Who knows maybe it has some good ideas that _can_ be inspired from sunglasses
> 
> Also I got this (_which is already a differentiator from [twtxt.net](https://twtxt.net) where we plan to fully automate and have 1-click pods that spin up instantaneously).
> 
> <img alt="Screen Shot 2020-08-06 at 22 14 20" width="809" src="https://user-images.githubusercontent.com/1290234/89530757-63a5dc00-d832-11ea-89d6-3f5241d9905d.png">
> 
> See #87

Why didn't you register on a public instance?

**Comment by prologic** [comment]
> Why didn't you register on a public instance?

Which one would you propose I register to? :) Not knowing the Mastodon community at all, I wouldn't have a clue where to go. There's no Aussie (Australian) instances I can find for example. So 🤷‍♂️ As I have said in this issue and elsewhere i'm pretty big on self-hosting actually. The fact that its actually quite hard to run up your own instance of Mastodon is already a big deal for me -- I've read through the docs and frankly its just "too hard". But I will try the Managed Hosted Mastodon and see what its like.

**Comment by prologic** [comment]
Okay so far so good. I guess I'm `@prologic@mastodon.mills.io` 👍 

I've taken lots of screen shots and taken care to carefully read everything I see and try to get a good feel of what its like.

My initial impressions/thoughts so far:

- Mastodon and twtxt are very similar except:
  - twtxt has the notion of user owned/managed feeds (_think of this as topics or personas you twt as_)
  - twtxt doesn't and cannot chain replies together, so there are no threads.
  - twtxt polls, rather than streams for updates to both local and external feeds

These are the key differences I see so far...

**Comment by prologic** [comment]
I just learned of another __very important__ difference here:

Let me quote:

> Your instance (Mastodon server) will only "know" of the existence of posts from people you follow. Plus, Mastodon doesn't fetch back posts. So, if for example you follow me now, your server will not "know" of my previous posts, only posts that I make after you follow me. The federation is a copy of the original posts that gets "pushed" to your server but it will only be "pushed" if you are a follower.
>
> So, Mastodon search is limited to posts your server "knows" about and only posts with hashtags, so it's normal it only returns 0 results because probably there are no posts with hashtags on the server, yet. You can test this by making a post with an hashtag and then doing a search. 
>
> The Federation Timeline is a timeline of all posts from local or remote users and if you are only following one user, until that user posts something you will only see local posts.

So I just learned of this from Hugo who setup my Managed Hosted instance for me (_thank you, hope you don't mind me quoting your!_); So here's the thing:

- twtxt polls and fetchs the full feed of a user or feed. It __does__ know of the existence of previous posts.

This is quite an important difference because when you say go create an account on [twtxt.net](https://twtxt.net (_we don't have hosted pods yet, that's coming soon™_); you immediately get access to the local timeline as well as external sources of feeds that are either configured or discovered. Once you start to follow one or more users, or external feeds your "network" grows immediately. Searches would work immediately (_if we had search_).

**Comment by prologic** [comment]
I am closing this issue as it is clear there are differences between Mastodon and Twtxt. Thank you all for the discussion.
